### ISSUE TITLE
Como Administrador, eu quero gerenciar os departamentos para que possa associar cursos a eles

### ISSUE THREAD

**Issue by Soraaslon** [ifspcodelab/gestao-estagios-backend#16]
Tarefas 

Critérios de aceitação

- [x]  Deve ser informado a sigla e o nome do departamento, além de em qual campus ele está contido
- [x]  A sigla deve seguir um padrão de três letras
- [x]  A sigla deve ser única para cada campus
- [x]  O departamento só poderá ser removido se não tiver nenhum curso associado a ele
- [x]  Um departamento só pode pertencer a um campus
- [x]  O departamento poderá ser desabilitado
- [x]  Opção de filtrar departamentos por campus
- [x]  Opção de filtrar departamentos desabilitados
