### ISSUE TITLE
Como Administrador, eu quero gerenciar os cursos para associar alunos e orientadores a eles

### ISSUE THREAD

**Issue by junnmu** [ifspcodelab/gestao-estagios-backend#17]
Tarefas

- [x] 1- Definir migração de curso
- [x] 1- Criar entidade de curso
- [x] 1- Criar repositório de curso
- [x] 5- Criar service de curso
- [x] 5- Criar controller de curso
- [ ] 1- Escrever testes para a entidade curso
- [ ] 3- Escrever testes para o repositório de curso
- [ ] 5- Escrever testes para o service de curso
- [ ] 5- Escrever testes para o controller de curso
- [x] 5- Criar interface de gerenciamento de cursos
- [x] 5- Criar service de curso no front-end

Critérios de Aceitação

- [x] O administrador deve informar o nome, sigla, quantidade de períodos, e o departamento que ele pertence
- [x] Um curso deve ter uma ou mais matrizes associadas a ele
- [x] Uma matriz deve possuir código, carga horária, carga horária de estágio obrigatório, critério para iniciar o estágio obrigatório e as atividades permitidas para estágio da matriz
- [x] A sigla deve ter no máximo 10 caracteres
- [x] A sigla deve ser única para cada departamento
- [x] Um curso só pode pertencer a um departamento
- [x] Os cursos devem ser exibidos em uma interface
- [x] A lista de cursos não deve conter interface de edição e detalhamento (master detail)
- [x] Filtro por cursos desabilitados
- [x] A exclusão só é possível desde que nenhum matriz pertença a ele
- [x] O curso poderá ser desabilitado
- [x] A matriz poderá ser desabilitada
