### ISSUE TITLE
Como Administrador, eu quero gerenciar dados do campus para que possa associar departamentos a eles.

### ISSUE THREAD

**Issue by epoiati** [ifspcodelab/gestao-estagios-backend#18]
**Tarefas**

**Critérios de Aceitação**

- [x] Deve  ser informado a sigla, nome e endereço do campus, telefone, e-mail e site do setor de estágio de cada campus
- [x] A sigla deve seguir um padrão de três letras
- [x] A sigla deve ser única
- [x] O campus só poderá ser removido do sistema se não tiver nenhum departamento associado a ele
- [x] O campus poderá ser desabilitado
- [x] Opção de filtrar campus desabilitados
